INGREDIENT_NAME_MAX_LEN = 200
MEASUREMENT_UNIT_NAME_MAX_LEN = 10

TAG_NAME_MAX_LEN = 200
TAG_SLUG_MAX_LEN = 200

RECIPE_NAME_MAX_LEN = 200

COOKING_TIME_MIN_VALUE = 1
COOKING_TIME_MAX_VALUE = 60

AMOUNT_INGREDIENT_MIN_VALUE = 1
AMOUNT_INGREDIENT_MAX_VALUE = 100
