version: '3.3'

volumes:
  pg_data:
  static:
  media:
  static_frontend:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: lexeyt/foodgram_backend:latest
    #build: ../backend/
    env_file: .env
    volumes:
      - static:/app/static_django/
      - media:/app/media/
    depends_on:
      - db 

  frontend:
    image: lexeyt/foodgram_frontend:latest
    volumes:
      - static_frontend:/app/result_build/

  nginx:
    image: nginx:1.19.3
    ports:
      - "8000:80"
#      - "80:80"
    volumes:
      - static:/static_django/
      - media:/media/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_frontend:/static_frontend/
      - ../docs/:/usr/share/nginx/html/api/docs/

    depends_on:
      - backend
      - frontend